[package]
name = "huo"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
description = "A fast and intuitive manga downloader CLI"

[[bin]]
name = "huo"
path = "src/main.rs"

[dependencies]
huo-core = { path = "../huo-core" }
clap = { workspace = true }
dialoguer = { workspace = true }
tokio = { workspace = true }

reqwest = { workspace = true }
dirs = { workspace = true }